version: '3.8'

services:
  app:
    image: learnedmachine/speakr:latest
    container_name: speakr
    restart: unless-stopped
    ports:
      - "8899:8899"
    volumes:
      - /path/to/uploads:/data/uploads
      - /path/to/instance:/data/instance
    environment:
      # Database and upload folder configuration
      - SQLALCHEMY_DATABASE_URI=sqlite:////data/instance/transcriptions.db
      - UPLOAD_FOLDER=/data/uploads
      
      # Text model configuration
      - TEXT_MODEL_BASE_URL=https://openrouter.ai/api/v1
      - TEXT_MODEL_API_KEY=your_text_model_api_key_here
      - TEXT_MODEL_NAME=openai/gpt-4o-mini
      
      # Whisper model configuration
      - TRANSCRIPTION_BASE_URL=http://your_local_api_url:port/v1/
      - TRANSCRIPTION_API_KEY=your_transcription_api_key_here
      - WHISPER_MODEL=Systran/faster-distil-whisper-large-v3
      
      # Application settings
      - ALLOW_REGISTRATION=false
      
      # Admin user creation
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=securepassword
