version: '3.8'

services:
  app:
    build: .
    image: speakr:latest
    container_name: speakr
    restart: unless-stopped
    ports:
      - "8899:8899"
    volumes:
      - /home/murtaza/whispertranscribe/uploads:/data/uploads
      - /home/murtaza/whispertranscribe/instance:/data/instance
    env_file:
      - .env
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:////data/instance/transcriptions.db
      - UPLOAD_FOLDER=/data/uploads
      # Admin user creation
      - ADMIN_USERNAME=murtaza
      - ADMIN_EMAIL=mail_speakr@nothanks.cc
      - ADMIN_PASSWORD=ukX8!jHKAR^XJN

volumes:
  speakr-uploads:
    name: speakr-uploads
  speakr-instance:
    name: speakr-instance
